// "use server"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css';
import HeaderPage from "./Header";
// import BannerPage from "./Pages/home/components/BannerPage";
import FooterPage from "./Footer";
import BuildContext from "./Dashboard/components/buildcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}>
        <BuildContext>
          <HeaderPage />
          <div className="container mx-auto">
            <main>
              {children}
            </main>
          </div>
          <FooterPage />
        </BuildContext>
      </body>
    </html>
  );
}
